config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: 'questions#ask', as: :ask
  get '/answer', to: 'questions#answer', as: :answer
end

app/models/application_record.rb
# Active Record
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
  end

  def answer
    if params[:question]
      @question = params[:question]
      @answer = "I don't care, get dressed and go to work!"
      @answer = 'Great!' if @question == "I'm going to work"
      @answer = 'Silly question, get dressed and go to work!' if @question.include?('?')
    end
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
  <h1>Stupid Coaching</h1>
<div class="grid-container container-lg">
 <div class="items">
   <h5>- You</h5>
   <h4> <%= @question %> </h4>
 </div>

  <div class='items'>
    <h5>- Your Coach</h5>
    <h4> <%= @answer %> </h4>
  </div>

  <%= link_to 'Ask a new question', ask_path %>
</div>

app/views/questions/ask.html.erb
<div class="grid-container container-sm" >

 <h1>Stupid coaching 🚀</h1>
 <h5>Ask your coach anything:</h5>

  <form action="/answer" method="get" class="row g-5">
    <div class="col-auto">
      <input type="text" name="question" class="form-control">
    </div>
    <div class="col-auto grid-item">
    <button type="submit" class="btn btn-warning mb-3" value="Ask!">Ask question !</button>
    </div>
  </form>
</div>